version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    # 1) Mapeia host:8000 → container:80 (Caddyfile.local escuta em :80)
    ports:
      - "8000:80"

    # 2) Monta Caddyfile.local sobre o Caddyfile interno do FrankenPHP
    volumes:
      - ./Caddyfile.local:/etc/frankenphp/Caddyfile:ro
      # monta o código da aplicação **com permissão de escrita**:
      - ./:/app

    # 3) Variáveis para habilitar debug e desativar HTTPS
    environment:
      # Faz o Lumen exibir erros em tela em vez de branco
      - APP_ENV=development
      - APP_DEBUG=true

      # Faz o Caddy (FrankenPHP) escutar só HTTP: porta 80
      - SERVER_NAME=:80
      - CADDY_GLOBAL_OPTIONS=auto_https disable_redirects
