version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce-llms-generator
    container_name: ecommerce-llms-generator
    environment:
      - SERVER_NAME=${SERVER_NAME:-localhost}
    volumes:
      - .:/app:ro
